### ISSUE TITLE
Incomplete Imports / Missing Packages

### ISSUE THREAD

**Issue by nilsgumpfer** [stephaneuler/game-simulator#1]
Hello Dr. Euler, 
we face following missing imports using those project-files:

jserver.XSendDE
jserver.Board
jserver.XSendAdapter
plotter.Sleep

Could you fix them / should we fix on our own?
Thank you in advance,

Nils Gumpfer

**Comment by stephaneuler** [comment]
Hello,

 I have added some information in the README. These classes are part of the Board of Symbols project.

Stephan Euler

**Comment by nilsgumpfer** [comment]
Thank you! :+1:
